development:
  adapter: postgresql
  encoding: unicode
  database: copasur_development
  pool: 5
  username: postgres
  password: devpass17

test:
  adapter: postgresql
  encoding: unicode
  database: copasur_test
  pool: 5
  username: postgres
  password: devpass17